services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
  minio:
    image: docker.io/bitnami/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001" #webui
    volumes:
      - minio-data:/bitnami/minio/data
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password
      - MINIO_SERVER_URL=http://0.0.0.0:9000

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"  # Exposes MongoDB on default port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: "27017"

volumes:
  mongodb_data:
  qdrant_data:
  minio-data:
